const data = [
  {
    tooltipText: `Cilj je da pre razgovora skupiš dovoljno informacija o korisniku, tj. stvoriš sliku šta bi tu sve moglo.`,
    categoryName: `Priprema`,
    stepAname: `Prodavac pregleda sve dostupne informacije koje vidi na ekranu (do kad traje i razlog UO, uređaj koji koristi, račun i stavke na njemu, aktivne/dostupne kampanje, tarifne dodatke, ako je prepaid broj: koliko često dopunjuje svoj broj).`,
    stepAcheckboxName: "P1A",
    stepBname: `Prodavac pregleda sve ugovore korisnika i sve informacije u vezi sa brojevima (do kad traje i razlog UO, uređaj koji koristi, račun i stavke na njemu, aktivne/dostupne kampanje, tarifne dodatke, ako je prepaid broj: koliko često dopunjuje svoj broj)`,
    stepBcheckboxName: "P1B",
  },
  {
    tooltipText: `Cilj je da uspostaviš prijatnu atmosferu i ton razgovora tako da zaintrigiraš korisnika da može nekako da te vizualizuje`,
    categoryName: "Predstavljanje",
    stepAname: `Prodavac se predstavlja tako što zvuči kao komšija koji se nalazi na korisniku dobro poznatoj lokaciji.`,
    stepAcheckboxName: "P2A",
    stepBname: `Prodavac otvara razgovor sa prijatnim pitanjem poput „kako ste“; „kako provodite vreme“ i sl.`,
    stepBcheckboxName: "P2B",
  },
  {
    tooltipText: `Cilj je da zaokupiš pažnju korisnika i stvoriš utisak kod korisnika da je poziv baš za njega i da je šteta da te ne čuje.`,
    categoryName: "Pecanje",
    stepAname: `Prodavac ne pita da li korisnik ima vremena već mudro kaže „verujem da imate 2 min...“`,
    stepAcheckboxName: "P3A",
    stepBname: `Prodavac peca korisnika koristeći reči poput popusti, novine, specijalne akcije, samo do kraja meseca, specijalna mogućnost za Vas i sl…`,
    stepBcheckboxName: "P3B",
  },
  {
    tooltipText: `Cilj je da shvatiš brzo u kom pravcu treba da povedeš razgovor. Ovo je rečenica ili pitanje koje služi da ne pričaš u prazno već da budeš efikasan.`,
    categoryName: "Pravac",
    stepAname: `Prodavac testira ideju šta bi tu sve moglo.`,
    stepAcheckboxName: "P4A",
    stepBname: `Prodavac brzo i spontano povede razgovor u drugom smeru ako ga korisnik odbije za prvu ideju.`,
    stepBcheckboxName: "P4B",
  },
  {
    tooltipText: `Cilj je da otkriješ prodajni potencijal – da saznaš šta sve korisniku treba`,
    categoryName: "Potencijal",
    stepAname: `Prodavac uključuje korisnika kroz prijatna pitanja kako bi mu stvorio želju za kupovinom.`,
    stepAcheckboxName: "P5A",
    stepBname: `Prodavac koristi jezik korisnika.`,
    stepBcheckboxName: "P5B",
  },
  {
    tooltipText: `Cilj je da kratko i efikasno predočiš benefit tj. osiguraš da korisnik zapamti zašto treba da dođe u prodavnicu/odgovori sa DA`,
    categoryName: "Ponuda",
    stepAname: `Prodavac se nadovezuje na ono što je čuo u prethodnom koraku.`,
    stepAcheckboxName: "P6A",
    stepBname: `Prodavac iznosi konkretnu ponudu i ne opterećuje korisnika svim cenama, načinima plaćanja i opcijama.`,
    stepBcheckboxName: "P6B",
  },
  {
    tooltipText: `Cilj je da osiguraš dolazak korisnika u prodavnicu/da odgovori sa DA`,
    categoryName: "Pozdrav",
    stepAname: `Prodavac zatvara razgovor prijatno tako da zna kada će korisnik doći u prodavnicu/ostaje na vezi dok korisnik odgovori sa DA.`,
    stepAcheckboxName: "P7A",
    stepBname: `Prodavac zadržava prijatan ton i ako korisnik nije zainteresovan ističući zašto je dobro da dođe u prodavnicu.`,
    stepBcheckboxName: "P7B",
  },
];

export default data;
